networks:
  service-network:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    environment:
      - API_URL=detection-service
      - API_PORT=5000
    ports:
      - "3000:3000"
    networks:
      - service-network
  detection-service:
    build:
      context: ./detection-service
      dockerfile: Dockerfile
    image: detection-service
    networks:
      - service-network
    depends_on:
      - db
  db:
    image: redis
    networks:
      - service-network
